using System.Collections.Generic;

namespace GrandiaStatEditor
{
    public class ItemListClass
    {
        public class ItemDrop
        {
            public int Value { get; set; }
            public string Text { get; set; }
        }

        public static List<ItemDrop> ItemDropList()
        {
            var itemList = new List<ItemDrop>()
            {
                new ItemDrop() { Value = 0, Text = "None" },
                new ItemDrop() { Value = 1, Text = "Prohibited" },
                new ItemDrop() { Value = 2, Text = "Prohibited" },
                new ItemDrop() { Value = 3, Text = "Prohibited" },
                new ItemDrop() { Value = 4, Text = "Prohibited" },
                new ItemDrop() { Value = 5, Text = "Prohibited" },
                new ItemDrop() { Value = 6, Text = "Prohibited" },
                new ItemDrop() { Value = 7, Text = "Prohibited" },
                new ItemDrop() { Value = 8, Text = "Prohibited" },
                new ItemDrop() { Value = 9, Text = "Prohibited" },
                new ItemDrop() { Value = 10, Text = "Spirit Stone" },
                new ItemDrop() { Value = 11, Text = "Hero's Armband" },
                new ItemDrop() { Value = 12, Text = "Horn of Knowledge" },
                new ItemDrop() { Value = 13, Text = "Medal of Wisdom" },
                new ItemDrop() { Value = 14, Text = "Medal of Knowledge" },
                new ItemDrop() { Value = 15, Text = "Gaia Sprout" },
                new ItemDrop() { Value = 16, Text = "Gantz's Key" },
                new ItemDrop() { Value = 17, Text = "Intro Letter" },
                new ItemDrop() { Value = 18, Text = "Key to the Cafe" },
                new ItemDrop() { Value = 19, Text = "Java's Wallet" },
                new ItemDrop() { Value = 20, Text = "Steamer Pass" },
                new ItemDrop() { Value = 21, Text = "Lilly's Letter" },
                new ItemDrop() { Value = 22, Text = "Cabin Key" },
                new ItemDrop() { Value = 23, Text = "Sulfa Weed" },
                new ItemDrop() { Value = 24, Text = "Jail Key" },
                new ItemDrop() { Value = 25, Text = "Master Key" },
                new ItemDrop() { Value = 26, Text = "Nectar of the Gods" },
                new ItemDrop() { Value = 27, Text = "Mist-Clearing Nut" },
                new ItemDrop() { Value = 28, Text = "Sue's Shoes" },
                new ItemDrop() { Value = 29, Text = "Warrior's Spear" },
                new ItemDrop() { Value = 30, Text = "Teleportation Orb" },
                new ItemDrop() { Value = 31, Text = "Apron" },
                new ItemDrop() { Value = 32, Text = "Pot Lid" },
                new ItemDrop() { Value = 33, Text = "Iron Pot" },
                new ItemDrop() { Value = 34, Text = "Wooden Sword" },
                new ItemDrop() { Value = 35, Text = "Spirit Sword" },
                new ItemDrop() { Value = 36, Text = "Biscuits" },
                new ItemDrop() { Value = 37, Text = "Marie's Pin" },
                new ItemDrop() { Value = 38, Text = "Coal Candy" },
                new ItemDrop() { Value = 39, Text = "Letter to Clara" },
                new ItemDrop() { Value = 40, Text = "Pearl" },
                new ItemDrop() { Value = 41, Text = "Rainbow Key" },
                new ItemDrop() { Value = 42, Text = "Boiled Egg" },
                new ItemDrop() { Value = 43, Text = "Chocolate" },
                new ItemDrop() { Value = 44, Text = "Jawbreaker" },
                new ItemDrop() { Value = 45, Text = "Ring of Protection" },
                new ItemDrop() { Value = 46, Text = "Frost Herb" },
                new ItemDrop() { Value = 47, Text = "Amulet of Relief" },
                new ItemDrop() { Value = 48, Text = "Prohibited" },
                new ItemDrop() { Value = 49, Text = "Prohibited" },
                new ItemDrop() { Value = 50, Text = "Prohibited" },
                new ItemDrop() { Value = 51, Text = "Prohibited" },
                new ItemDrop() { Value = 52, Text = "Prohibited" },
                new ItemDrop() { Value = 53, Text = "Prohibited" },
                new ItemDrop() { Value = 54, Text = "Prohibited" },
                new ItemDrop() { Value = 55, Text = "Prohibited" },
                new ItemDrop() { Value = 56, Text = "Prohibited" },
                new ItemDrop() { Value = 57, Text = "Prohibited" },
                new ItemDrop() { Value = 58, Text = "Prohibited" },
                new ItemDrop() { Value = 59, Text = "Prohibited" },
                new ItemDrop() { Value = 60, Text = "Prohibited" },
                new ItemDrop() { Value = 61, Text = "Prohibited" },
                new ItemDrop() { Value = 62, Text = "Prohibited" },
                new ItemDrop() { Value = 63, Text = "Knife of Judgment" },
                new ItemDrop() { Value = 64, Text = "Rusty Knife" },
                new ItemDrop() { Value = 65, Text = "Paring Knife" },
                new ItemDrop() { Value = 66, Text = "Hunter's Knife" },
                new ItemDrop() { Value = 67, Text = "Flint Knife" },
                new ItemDrop() { Value = 68, Text = "Azure Knife" },
                new ItemDrop() { Value = 69, Text = "Shocking Knife" },
                new ItemDrop() { Value = 70, Text = "Poisoned Knife" },
                new ItemDrop() { Value = 71, Text = "Assassin's Dagger" },
                new ItemDrop() { Value = 72, Text = "Bloody Knife" },
                new ItemDrop() { Value = 73, Text = "Ice Pick" },
                new ItemDrop() { Value = 74, Text = "Force Knife" },
                new ItemDrop() { Value = 75, Text = "Godspeed Knife" },
                new ItemDrop() { Value = 76, Text = "Gust Knife" },
                new ItemDrop() { Value = 77, Text = "Ruination Knife" },
                new ItemDrop() { Value = 78, Text = "Thief Cutter" },
                new ItemDrop() { Value = 79, Text = "Zero Knife" },
                new ItemDrop() { Value = 80, Text = "Ceramic Sword" },
                new ItemDrop() { Value = 81, Text = "Prohibited" },
                new ItemDrop() { Value = 82, Text = "Admiral's Sword" },
                new ItemDrop() { Value = 83, Text = "Great Sword" },
                new ItemDrop() { Value = 84, Text = "Army Saber" },
                new ItemDrop() { Value = 85, Text = "The Sword Himmler" },
                new ItemDrop() { Value = 86, Text = "Angel's Darts" },
                new ItemDrop() { Value = 87, Text = "Swordfish Sword" },
                new ItemDrop() { Value = 88, Text = "Dragon Killer" },
                new ItemDrop() { Value = 89, Text = "Fire Sword" },
                new ItemDrop() { Value = 90, Text = "Shadow Sword" },
                new ItemDrop() { Value = 91, Text = "Gil Sword" },
                new ItemDrop() { Value = 92, Text = "Silence Sword" },
                new ItemDrop() { Value = 93, Text = "Prohibited" },
                new ItemDrop() { Value = 94, Text = "Wobbly Sword" },
                new ItemDrop() { Value = 95, Text = "Main Gauche" },
                new ItemDrop() { Value = 96, Text = "Holy Sword Lorenzo" },
                new ItemDrop() { Value = 97, Text = "Ice Blade" },
                new ItemDrop() { Value = 98, Text = "Lightning Sword" },
                new ItemDrop() { Value = 99, Text = "Battle Saber" },
                new ItemDrop() { Value = 100, Text = "Zero Sword" },
                new ItemDrop() { Value = 101, Text = "Wooden Pole" },
                new ItemDrop() { Value = 102, Text = "Metal Bat" },
                new ItemDrop() { Value = 103, Text = "Zero Rod" },
                new ItemDrop() { Value = 104, Text = "Officer's Baton" },
                new ItemDrop() { Value = 105, Text = "Magic Rod" },
                new ItemDrop() { Value = 106, Text = "Miner's Hammer" },
                new ItemDrop() { Value = 107, Text = "Iron Mace" },
                new ItemDrop() { Value = 108, Text = "Army Darts" },
                new ItemDrop() { Value = 109, Text = "Lassic Hammer" },
                new ItemDrop() { Value = 110, Text = "War Hammer" },
                new ItemDrop() { Value = 111, Text = "Hertz Spike" },
                new ItemDrop() { Value = 112, Text = "Oracle's Staff" },
                new ItemDrop() { Value = 113, Text = "Raincloud Staff" },
                new ItemDrop() { Value = 114, Text = "Staff of Life" },
                new ItemDrop() { Value = 115, Text = "Warp Staff" },
                new ItemDrop() { Value = 116, Text = "Holy Mace" },
                new ItemDrop() { Value = 117, Text = "Fire Rod" },
                new ItemDrop() { Value = 118, Text = "Aromatic Tree Root" },
                new ItemDrop() { Value = 119, Text = "Sparkling Rod" },
                new ItemDrop() { Value = 120, Text = "Spirit Staff" },
                new ItemDrop() { Value = 121, Text = "Home Run Hammer" },
                new ItemDrop() { Value = 122, Text = "Rusty Shovel" },
                new ItemDrop() { Value = 123, Text = "Ceremonial Rock Ax" },
                new ItemDrop() { Value = 124, Text = "Big Hatchet" },
                new ItemDrop() { Value = 125, Text = "Woodchopper's Ax" },
                new ItemDrop() { Value = 126, Text = "Dragon Bone Ax" },
                new ItemDrop() { Value = 127, Text = "Bone Splitter Ax" },
                new ItemDrop() { Value = 128, Text = "Klepp's Sickle" },
                new ItemDrop() { Value = 129, Text = "Frog Ax" },
                new ItemDrop() { Value = 130, Text = "Earthen Ax" },
                new ItemDrop() { Value = 131, Text = "Buster Ax" },
                new ItemDrop() { Value = 132, Text = "Bent Mattock" },
                new ItemDrop() { Value = 133, Text = "Wrecking Ax" },
                new ItemDrop() { Value = 134, Text = "Hand Ax" },
                new ItemDrop() { Value = 135, Text = "Zero Ax" },
                new ItemDrop() { Value = 136, Text = "Toy Bow and Arrow" },
                new ItemDrop() { Value = 137, Text = "Handmade Darts" },
                new ItemDrop() { Value = 138, Text = "Hunter's Bow" },
                new ItemDrop() { Value = 139, Text = "Flying Fish Bow" },
                new ItemDrop() { Value = 140, Text = "Hail Bow" },
                new ItemDrop() { Value = 141, Text = "Flint Bow" },
                new ItemDrop() { Value = 142, Text = "Exorcising Bow" },
                new ItemDrop() { Value = 143, Text = "Cafu Shuriken" },
                new ItemDrop() { Value = 144, Text = "Boomerang" },
                new ItemDrop() { Value = 145, Text = "Evil Shuriken" },
                new ItemDrop() { Value = 146, Text = "Demonslayer Boomer" },
                new ItemDrop() { Value = 147, Text = "Discus" },
                new ItemDrop() { Value = 148, Text = "Cactus Thorns" },
                new ItemDrop() { Value = 149, Text = "Fire Darts" },
                new ItemDrop() { Value = 150, Text = "Ice Boomerang" },
                new ItemDrop() { Value = 151, Text = "Thunder Arrow" },
                new ItemDrop() { Value = 152, Text = "Zero Shuriken" },
                new ItemDrop() { Value = 153, Text = "Zero Whip" },
                new ItemDrop() { Value = 154, Text = "Mist-Cracking Whip" },
                new ItemDrop() { Value = 155, Text = "Leather Whip" },
                new ItemDrop() { Value = 156, Text = "Thorny Whip" },
                new ItemDrop() { Value = 157, Text = "Catfish Whiskers" },
                new ItemDrop() { Value = 158, Text = "Giant Snake Whip" },
                new ItemDrop() { Value = 159, Text = "Binding Whip" },
                new ItemDrop() { Value = 160, Text = "Morning Star" },
                new ItemDrop() { Value = 161, Text = "Whip of Light" },
                new ItemDrop() { Value = 162, Text = "Burning Hot Whip" },
                new ItemDrop() { Value = 163, Text = "Gale Whip" },
                new ItemDrop() { Value = 164, Text = "Adventure Clothes" },
                new ItemDrop() { Value = 165, Text = "Sunday Best" },
                new ItemDrop() { Value = 166, Text = "Sportswear" },
                new ItemDrop() { Value = 167, Text = "Work Clothes" },
                new ItemDrop() { Value = 168, Text = "Cactus Armor" },
                new ItemDrop() { Value = 169, Text = "Soldier's Uniform" },
                new ItemDrop() { Value = 170, Text = "Officer's Uniform" },
                new ItemDrop() { Value = 171, Text = "Fairy Robe" },
                new ItemDrop() { Value = 172, Text = "Flying Dragon Vest" },
                new ItemDrop() { Value = 173, Text = "Frog Shirt" },
                new ItemDrop() { Value = 174, Text = "Spy Clothes" },
                new ItemDrop() { Value = 175, Text = "Chain Mail" },
                new ItemDrop() { Value = 176, Text = "Battle Bikini" },
                new ItemDrop() { Value = 177, Text = "Mogay Clothes" },
                new ItemDrop() { Value = 178, Text = "Mink Coat" },
                new ItemDrop() { Value = 179, Text = "Enchantress' Robe" },
                new ItemDrop() { Value = 180, Text = "Angel's Robe" },
                new ItemDrop() { Value = 181, Text = "Robe of the Sun" },
                new ItemDrop() { Value = 182, Text = "Breastplate" },
                new ItemDrop() { Value = 183, Text = "Outdated Armor" },
                new ItemDrop() { Value = 184, Text = "Bamboo Armor" },
                new ItemDrop() { Value = 185, Text = "Shell Armor" },
                new ItemDrop() { Value = 186, Text = "Thick Armor" },
                new ItemDrop() { Value = 187, Text = "Swordfish Armor" },
                new ItemDrop() { Value = 188, Text = "Skull Armor" },
                new ItemDrop() { Value = 189, Text = "Chameleon Armor" },
                new ItemDrop() { Value = 190, Text = "Plug Suit" },
                new ItemDrop() { Value = 191, Text = "Aura Armor" },
                new ItemDrop() { Value = 192, Text = "Dark Armor" },
                new ItemDrop() { Value = 193, Text = "Warrior's Mail" },
                new ItemDrop() { Value = 194, Text = "Spirit Armor" },
                new ItemDrop() { Value = 195, Text = "Devil's Robe" },
                new ItemDrop() { Value = 196, Text = "Magic Robe" },
                new ItemDrop() { Value = 197, Text = "Cutting Board" },
                new ItemDrop() { Value = 198, Text = "Woolen Mittens" },
                new ItemDrop() { Value = 199, Text = "Leather Gloves" },
                new ItemDrop() { Value = 200, Text = "Escargot Shield" },
                new ItemDrop() { Value = 201, Text = "Oaken Shield" },
                new ItemDrop() { Value = 202, Text = "Shell Shield" },
                new ItemDrop() { Value = 203, Text = "Seashell Shield" },
                new ItemDrop() { Value = 204, Text = "Mushroom Shield" },
                new ItemDrop() { Value = 205, Text = "MagicMirror Shield" },
                new ItemDrop() { Value = 206, Text = "Alligator Gauntlet" },
                new ItemDrop() { Value = 207, Text = "Leaf Shield" },
                new ItemDrop() { Value = 208, Text = "Lafa Flower Shield" },
                new ItemDrop() { Value = 209, Text = "Power Shield" },
                new ItemDrop() { Value = 210, Text = "Moonlight Shield" },
                new ItemDrop() { Value = 211, Text = "Gauntlets" },
                new ItemDrop() { Value = 212, Text = "Dragon Gauntlet" },
                new ItemDrop() { Value = 213, Text = "Heavy Shield" },
                new ItemDrop() { Value = 214, Text = "Gauntlets of Light" },
                new ItemDrop() { Value = 215, Text = "Spirit Shield" },
                new ItemDrop() { Value = 216, Text = "Magic Gloves" },
                new ItemDrop() { Value = 217, Text = "Zero Shield" },
                new ItemDrop() { Value = 218, Text = "Goggles" },
                new ItemDrop() { Value = 219, Text = "Ribbon" },
                new ItemDrop() { Value = 220, Text = "Fluffy Ribbon" },
                new ItemDrop() { Value = 221, Text = "Barrette" },
                new ItemDrop() { Value = 222, Text = "Pirate's Hat" },
                new ItemDrop() { Value = 223, Text = "Cowboy Hat" },
                new ItemDrop() { Value = 224, Text = "Climbing Hat" },
                new ItemDrop() { Value = 225, Text = "Odd Hat" },
                new ItemDrop() { Value = 226, Text = "Headgear" },
                new ItemDrop() { Value = 227, Text = "Iron Bandana" },
                new ItemDrop() { Value = 228, Text = "Feathered Turban" },
                new ItemDrop() { Value = 229, Text = "Angel's Hat" },
                new ItemDrop() { Value = 230, Text = "Pope's Hat" },
                new ItemDrop() { Value = 231, Text = "Safety Helmet" },
                new ItemDrop() { Value = 232, Text = "Antler Helmet" },
                new ItemDrop() { Value = 233, Text = "Pearl Helmet" },
                new ItemDrop() { Value = 234, Text = "Pirate's Helmet" },
                new ItemDrop() { Value = 235, Text = "Stone Head" },
                new ItemDrop() { Value = 236, Text = "Swallowtail Hat" },
                new ItemDrop() { Value = 237, Text = "Mystic Mask" },
                new ItemDrop() { Value = 238, Text = "Death Mask" },
                new ItemDrop() { Value = 239, Text = "Ogre Helm" },
                new ItemDrop() { Value = 240, Text = "Charisma Helm" },
                new ItemDrop() { Value = 241, Text = "Spirit Helmet" },
                new ItemDrop() { Value = 242, Text = "Holy Crown" },
                new ItemDrop() { Value = 243, Text = "Cactus Helm" },
                new ItemDrop() { Value = 244, Text = "Fairy Tiara" },
                new ItemDrop() { Value = 245, Text = "Man's Headband" },
                new ItemDrop() { Value = 246, Text = "Battle Helm" },
                new ItemDrop() { Value = 247, Text = "Sneakers" },
                new ItemDrop() { Value = 248, Text = "Dress Shoes" },
                new ItemDrop() { Value = 249, Text = "Air Sneakers" },
                new ItemDrop() { Value = 250, Text = "Shiny Shoes" },
                new ItemDrop() { Value = 251, Text = "Rubber Boots" },
                new ItemDrop() { Value = 252, Text = "Leather Greaves" },
                new ItemDrop() { Value = 253, Text = "Hunter's Boots" },
                new ItemDrop() { Value = 254, Text = "Army Boots" },
                new ItemDrop() { Value = 255, Text = "Curious Clogs" },
                new ItemDrop() { Value = 256, Text = "Dragon Boots" },
                new ItemDrop() { Value = 257, Text = "Ninja Sandals" },
                new ItemDrop() { Value = 258, Text = "Winged Boots" },
                new ItemDrop() { Value = 259, Text = "Beach Sandals" },
                new ItemDrop() { Value = 260, Text = "Mach 1 Boots" },
                new ItemDrop() { Value = 261, Text = "Heavy Boots" },
                new ItemDrop() { Value = 262, Text = "Queen Heels" },
                new ItemDrop() { Value = 263, Text = "Iron Clogs" },
                new ItemDrop() { Value = 264, Text = "Ogre Boots" },
                new ItemDrop() { Value = 265, Text = "Rabbit Shoes" },
                new ItemDrop() { Value = 266, Text = "Rainbow High Heels" },
                new ItemDrop() { Value = 267, Text = "Wolf Boots" },
                new ItemDrop() { Value = 268, Text = "Lion Boots" },
                new ItemDrop() { Value = 269, Text = "Battle Boots" },
                new ItemDrop() { Value = 270, Text = "Spirit Shoes" },
                new ItemDrop() { Value = 271, Text = "Glass Slippers" },
                new ItemDrop() { Value = 272, Text = "Warp Shoes" },
                new ItemDrop() { Value = 273, Text = "Crampons" },
                new ItemDrop() { Value = 274, Text = "Zero Boots" },
                new ItemDrop() { Value = 275, Text = "Prohibited" },
                new ItemDrop() { Value = 276, Text = "Diana's Amulet" },
                new ItemDrop() { Value = 277, Text = "Hero's Badge" },
                new ItemDrop() { Value = 278, Text = "Demon Sword Amulet" },
                new ItemDrop() { Value = 279, Text = "Officer's Badge" },
                new ItemDrop() { Value = 280, Text = "Black Belt" },
                new ItemDrop() { Value = 281, Text = "Chain Earrings" },
                new ItemDrop() { Value = 282, Text = "Titan's Ring" },
                new ItemDrop() { Value = 283, Text = "Fireproof Cape" },
                new ItemDrop() { Value = 284, Text = "Fire Charm" },
                new ItemDrop() { Value = 285, Text = "Water Charm" },
                new ItemDrop() { Value = 286, Text = "Wind Charm" },
                new ItemDrop() { Value = 287, Text = "Earth Charm" },
                new ItemDrop() { Value = 288, Text = "Counter Ring" },
                new ItemDrop() { Value = 289, Text = "Secret Move Ring" },
                new ItemDrop() { Value = 290, Text = "Hurricane Belt" },
                new ItemDrop() { Value = 291, Text = "Mama's Amulet" },
                new ItemDrop() { Value = 292, Text = "Jade Charm" },
                new ItemDrop() { Value = 293, Text = "Tree God Amulet" },
                new ItemDrop() { Value = 294, Text = "Light God Amulet" },
                new ItemDrop() { Value = 295, Text = "Ancestor's Amulet" },
                new ItemDrop() { Value = 296, Text = "Raincoat" },
                new ItemDrop() { Value = 297, Text = "Iridescent Amulet" },
                new ItemDrop() { Value = 298, Text = "Move Unblocker" },
                new ItemDrop() { Value = 299, Text = "Medal of Yore" },
                new ItemDrop() { Value = 300, Text = "Spirit Charm" },
                new ItemDrop() { Value = 301, Text = "Phantom Silk" },
                new ItemDrop() { Value = 302, Text = "Lightning Charm" },
                new ItemDrop() { Value = 303, Text = "Forest Charm" },
                new ItemDrop() { Value = 304, Text = "Explosion Charm" },
                new ItemDrop() { Value = 305, Text = "Blizzard Charm" },
                new ItemDrop() { Value = 306, Text = "Wind Belt" },
                new ItemDrop() { Value = 307, Text = "Confusion Charm" },
                new ItemDrop() { Value = 308, Text = "Paralysis Charm" },
                new ItemDrop() { Value = 309, Text = "Magic Block Charm" },
                new ItemDrop() { Value = 310, Text = "Sudden Death Charm" },
                new ItemDrop() { Value = 311, Text = "Poison Charm" },
                new ItemDrop() { Value = 312, Text = "Talisman" },
                new ItemDrop() { Value = 313, Text = "Sonic Belt" },
                new ItemDrop() { Value = 314, Text = "Metal Frog" },
                new ItemDrop() { Value = 315, Text = "Revival Stone" },
                new ItemDrop() { Value = 316, Text = "Use Prohibited" },
                new ItemDrop() { Value = 317, Text = "Scarab" },
                new ItemDrop() { Value = 318, Text = "Demon Eye Stone" },
                new ItemDrop() { Value = 319, Text = "Jewel of Life" },
                new ItemDrop() { Value = 320, Text = "Ankh of Temptation" },
                new ItemDrop() { Value = 321, Text = "Anklet" },
                new ItemDrop() { Value = 322, Text = "Energy Ring" },
                new ItemDrop() { Value = 323, Text = "Disease Charm" },
                new ItemDrop() { Value = 324, Text = "Paperweight" },
                new ItemDrop() { Value = 325, Text = "Combat Anklet" },
                new ItemDrop() { Value = 326, Text = "Chain of Gems" },
                new ItemDrop() { Value = 327, Text = "Satisfaction Gem" },
                new ItemDrop() { Value = 328, Text = "Soul of Asura" },
                new ItemDrop() { Value = 329, Text = "Crescent Jade" },
                new ItemDrop() { Value = 330, Text = "Dragon Scales" },
                new ItemDrop() { Value = 331, Text = "Spectacles" },
                new ItemDrop() { Value = 332, Text = "Rune Ring" },
                new ItemDrop() { Value = 333, Text = "Tear Jewel" },
                new ItemDrop() { Value = 334, Text = "Spirit Potion" },
                new ItemDrop() { Value = 335, Text = "Wound Salve" },
                new ItemDrop() { Value = 336, Text = "Baobab Fruit" },
                new ItemDrop() { Value = 337, Text = "Boiled Coconut" },
                new ItemDrop() { Value = 338, Text = "Chocolate Cookies" },
                new ItemDrop() { Value = 339, Text = "Honey" },
                new ItemDrop() { Value = 340, Text = "Ultra Drink" },
                new ItemDrop() { Value = 341, Text = "Weeds" },
                new ItemDrop() { Value = 342, Text = "Dried Fish" },
                new ItemDrop() { Value = 343, Text = "Bamboo Shoots" },
                new ItemDrop() { Value = 344, Text = "Beef Jerky" },
                new ItemDrop() { Value = 345, Text = "Box Lunch" },
                new ItemDrop() { Value = 346, Text = "Herbs" },
                new ItemDrop() { Value = 347, Text = "White Sulfa Weed" },
                new ItemDrop() { Value = 348, Text = "Smarna Weed" },
                new ItemDrop() { Value = 349, Text = "Cholla Flowers" },
                new ItemDrop() { Value = 350, Text = "Bamo Fruit" },
                new ItemDrop() { Value = 351, Text = "Squid Guts" },
                new ItemDrop() { Value = 352, Text = "Move Mushroom" },
                new ItemDrop() { Value = 353, Text = "Power Mushroom" },
                new ItemDrop() { Value = 354, Text = "Poison Antidote" },
                new ItemDrop() { Value = 355, Text = "Ginseng" },
                new ItemDrop() { Value = 356, Text = "Banana" },
                new ItemDrop() { Value = 357, Text = "Bandage" },
                new ItemDrop() { Value = 358, Text = "Box of Sweets" },
                new ItemDrop() { Value = 359, Text = "First Aid Kit" },
                new ItemDrop() { Value = 360, Text = "Red Medicine" },
                new ItemDrop() { Value = 361, Text = "Blue Medicine" },
                new ItemDrop() { Value = 362, Text = "Yellow Medicine" },
                new ItemDrop() { Value = 363, Text = "Crimson Potion" },
                new ItemDrop() { Value = 364, Text = "Deep Blue Potion" },
                new ItemDrop() { Value = 365, Text = "Golden Potion" },
                new ItemDrop() { Value = 366, Text = "Magic Lamp" },
                new ItemDrop() { Value = 367, Text = "Poison Antidote" },
                new ItemDrop() { Value = 368, Text = "Vaccine" },
                new ItemDrop() { Value = 369, Text = "Eye Drops" },
                new ItemDrop() { Value = 370, Text = "Smelling Salts" },
                new ItemDrop() { Value = 371, Text = "Paralysis Ointment" },
                new ItemDrop() { Value = 372, Text = "Spell Breaker" },
                new ItemDrop() { Value = 373, Text = "Move Breaker" },
                new ItemDrop() { Value = 374, Text = "Resurrect Potion" },
                new ItemDrop() { Value = 375, Text = "Panacea" },
                new ItemDrop() { Value = 376, Text = "Bond of Trust" },
                new ItemDrop() { Value = 377, Text = "Seed of Power" },
                new ItemDrop() { Value = 378, Text = "Seed of Defense" },
                new ItemDrop() { Value = 379, Text = "Seed of Speed" },
                new ItemDrop() { Value = 380, Text = "Seed of Running" },
                new ItemDrop() { Value = 381, Text = "All-Around Seed" },
                new ItemDrop() { Value = 382, Text = "Seed of Life" },
                new ItemDrop() { Value = 383, Text = "Seed of Magic" },
                new ItemDrop() { Value = 384, Text = "Seed of Moves" },
                new ItemDrop() { Value = 385, Text = "Mace Coloring Book" },
                new ItemDrop() { Value = 386, Text = "Bow Coloring Book" },
                new ItemDrop() { Value = 387, Text = "Sword Secrets" },
                new ItemDrop() { Value = 388, Text = "Fire Secrets" },
                new ItemDrop() { Value = 389, Text = "Earth Secrets" },
                new ItemDrop() { Value = 390, Text = "How to Cut 'Em" },
                new ItemDrop() { Value = 391, Text = "How to Pound 'Em" },
                new ItemDrop() { Value = 392, Text = "How to Chop 'Em" },
                new ItemDrop() { Value = 393, Text = "Roach Bomb" },
                new ItemDrop() { Value = 394, Text = "Firewood Sparks" },
                new ItemDrop() { Value = 395, Text = "Mana Egg" },
                new ItemDrop() { Value = 396, Text = "Holy Fire" },
                new ItemDrop() { Value = 397, Text = "Hand Grenade" },
                new ItemDrop() { Value = 398, Text = "Dynamite" },
                new ItemDrop() { Value = 399, Text = "Rocket Fireworks" },
                new ItemDrop() { Value = 400, Text = "Launch Fireworks" },
                new ItemDrop() { Value = 401, Text = "BOOM! Scroll" },
                new ItemDrop() { Value = 402, Text = "Howler Scroll" },
                new ItemDrop() { Value = 403, Text = "Vacuum Scroll" },
                new ItemDrop() { Value = 404, Text = "Tremor Scroll" },
                new ItemDrop() { Value = 405, Text = "Zap! Book" },
                new ItemDrop() { Value = 406, Text = "Lightning Scroll" },
                new ItemDrop() { Value = 407, Text = "Gale Scroll" },
                new ItemDrop() { Value = 408, Text = "Overflowing Walnut" },
                new ItemDrop() { Value = 409, Text = "Restraint Walnut" },
                new ItemDrop() { Value = 410, Text = "Sonic Walnut" },
                new ItemDrop() { Value = 411, Text = "Running Walnut" },
                new ItemDrop() { Value = 412, Text = "Snooze Scroll" },
                new ItemDrop() { Value = 413, Text = "Poisoned Apple" },
                new ItemDrop() { Value = 414, Text = "Culture Medium" },
                new ItemDrop() { Value = 415, Text = "Dream Truffle" },
                new ItemDrop() { Value = 416, Text = "Paralyze Mushroom" },
                new ItemDrop() { Value = 417, Text = "Orb of Silence" },
                new ItemDrop() { Value = 418, Text = "Black Onyx" },
                new ItemDrop() { Value = 419, Text = "Weak-Knee Weed" },
                new ItemDrop() { Value = 420, Text = "Ragged Weed" },
                new ItemDrop() { Value = 421, Text = "Slouch Weed" },
                new ItemDrop() { Value = 422, Text = "Trudge Weed" },
                new ItemDrop() { Value = 423, Text = "Root of Confusion" },
                new ItemDrop() { Value = 424, Text = "Torte's Whistle" },
                new ItemDrop() { Value = 425, Text = "Freesia Flowers" },
                new ItemDrop() { Value = 426, Text = "Cone of Light" },
                new ItemDrop() { Value = 427, Text = "Mikeroma Scroll" },
                new ItemDrop() { Value = 428, Text = "Shuffle Card" },
                new ItemDrop() { Value = 429, Text = "Miracle Drink" },
                new ItemDrop() { Value = 430, Text = "Gold Key" },
                new ItemDrop() { Value = 431, Text = "Silver Key" },
                new ItemDrop() { Value = 432, Text = "Key of Temptation" },
                new ItemDrop() { Value = 433, Text = "Soldier's Key" },
                new ItemDrop() { Value = 434, Text = "Pretty Jewel" },
                new ItemDrop() { Value = 435, Text = "Pretty Jewel" },
                new ItemDrop() { Value = 436, Text = "Pretty Jewel" },
                new ItemDrop() { Value = 437, Text = "Horn of Inogon" },
                new ItemDrop() { Value = 438, Text = "Key" },
                new ItemDrop() { Value = 439, Text = "Health Weed" },
                new ItemDrop() { Value = 440, Text = "Snake Earrings" },
                new ItemDrop() { Value = 441, Text = "Resurrect Potion" },
                new ItemDrop() { Value = 442, Text = "Expensive Jewel" },
                new ItemDrop() { Value = 443, Text = "Rainbow Weed" },
                new ItemDrop() { Value = 444, Text = "Smoked Salmon" },
                new ItemDrop() { Value = 445, Text = "Prime Rib" },
                new ItemDrop() { Value = 446, Text = "Rescue Set" },
                new ItemDrop() { Value = 447, Text = "Black Nail Polish" },
                new ItemDrop() { Value = 448, Text = "Prohibited" },
                new ItemDrop() { Value = 449, Text = "Thor's Fury" },
                new ItemDrop() { Value = 450, Text = "Magic Lipstick" },
                new ItemDrop() { Value = 451, Text = "Elite Badge" },
                new ItemDrop() { Value = 452, Text = "Fruit of Power" },
                new ItemDrop() { Value = 453, Text = "Fruit of Defense" },
                new ItemDrop() { Value = 454, Text = "Fruit of Speed" },
                new ItemDrop() { Value = 455, Text = "Fruit of Agility" },
                new ItemDrop() { Value = 456, Text = "All-Around Fruit" },
                new ItemDrop() { Value = 457, Text = "Fruit of Life" },
                new ItemDrop() { Value = 458, Text = "Fruit of Magic" },
                new ItemDrop() { Value = 459, Text = "Fruit of Moves" },
                new ItemDrop() { Value = 460, Text = "Mogay Teachings 1" },
                new ItemDrop() { Value = 461, Text = "Mogay Teachings 2" },
                new ItemDrop() { Value = 462, Text = "Mogay Teachings 3" },
                new ItemDrop() { Value = 463, Text = "Ring of Rage" },
                new ItemDrop() { Value = 464, Text = "Holy Ring" },
                new ItemDrop() { Value = 465, Text = "Mysterious Veil" },
                new ItemDrop() { Value = 466, Text = "Blizzard Scroll" },
                new ItemDrop() { Value = 467, Text = "Telescope" },
                new ItemDrop() { Value = 468, Text = "Energy Charm" },
                new ItemDrop() { Value = 469, Text = "Devil's Anklet" },
                new ItemDrop() { Value = 470, Text = "Prohibited" },
                new ItemDrop() { Value = 471, Text = "Astral Miracle" },
                new ItemDrop() { Value = 472, Text = "Ethereal Miracle" },
                new ItemDrop() { Value = 473, Text = "Miraculous Scales" },
                new ItemDrop() { Value = 474, Text = "General's Staff" },
                new ItemDrop() { Value = 475, Text = "Brown Crayon" },
                new ItemDrop() { Value = 476, Text = "Blue Crayon" },
                new ItemDrop() { Value = 477, Text = "Red Crayon" },
                new ItemDrop() { Value = 478, Text = "Sky-Blue Crayon" },
                new ItemDrop() { Value = 479, Text = "Emperor's Whip" },
                new ItemDrop() { Value = 480, Text = "Soldier's Soul" },
                new ItemDrop() { Value = 481, Text = "Poison of Power" },
                new ItemDrop() { Value = 482, Text = "Poison of Defense" },
                new ItemDrop() { Value = 483, Text = "Poison of Speed" },
                new ItemDrop() { Value = 484, Text = "Poison of Agility" },
                new ItemDrop() { Value = 485, Text = "All-Around Poison" },
                new ItemDrop() { Value = 486, Text = "Poison of Life" },
                new ItemDrop() { Value = 487, Text = "Poison of Magic" },
                new ItemDrop() { Value = 488, Text = "Poison of Moves" },
                new ItemDrop() { Value = 489, Text = "+1 Dagger Skill" },
                new ItemDrop() { Value = 490, Text = "+5 Dagger Skill" },
                new ItemDrop() { Value = 491, Text = "+1 Sword Skill" },
                new ItemDrop() { Value = 492, Text = "+5 Sword Skill" },
                new ItemDrop() { Value = 493, Text = "+1 Mace Skill" },
                new ItemDrop() { Value = 494, Text = "+5 Mace Skill" },
                new ItemDrop() { Value = 495, Text = "+1 Ax Skill" },
                new ItemDrop() { Value = 496, Text = "+5 Ax Skill" },
                new ItemDrop() { Value = 497, Text = "+1 Whip Skill" },
                new ItemDrop() { Value = 498, Text = "+5 Whip Skill" },
                new ItemDrop() { Value = 499, Text = "+1 Bow Skill" },
                new ItemDrop() { Value = 500, Text = "+5 Bow Skill" },
                new ItemDrop() { Value = 501, Text = "+1 Fire Skill" },
                new ItemDrop() { Value = 502, Text = "+5 Fire Skill" },
                new ItemDrop() { Value = 503, Text = "+1 Wind Skill" },
                new ItemDrop() { Value = 504, Text = "+5 Wind Skill" },
                new ItemDrop() { Value = 505, Text = "+1 Water Skill" },
                new ItemDrop() { Value = 506, Text = "+5 Water Skill" },
                new ItemDrop() { Value = 507, Text = "+1 Earth Skill" },
                new ItemDrop() { Value = 508, Text = "+5 Earth Skill" },
                new ItemDrop() { Value = 509, Text = "100 Sword" },
                new ItemDrop() { Value = 510, Text = "100 Mace" },
                new ItemDrop() { Value = 511, Text = "100 Fire Mace" }
            };

            return itemList;
        }
    }
}
